### ISSUE TITLE
PLS-00753: malformed or corrupted wrapped unit

### ISSUE THREAD

**Issue by p3t3r** [antonscheffer/APEX2XLSX#2]
The function APEX2XLSX is invalid after installing the plugin.
The error:
PLS-00753: malformed or corrupted wrapped unit

**Comment by antonscheffer** [comment]
It does help that you load all lines of a dynamic installed function :) Increased the number of loaded lines to 25000 and updated the plugin.

**Comment by p3t3r** [comment]
Removed function and plugin, reinstalled, but now the error is:
PLS-00201: identifier 'APEX2XLSX' must be declared

**Comment by antonscheffer** [comment]
Hhm, I'm certain that the current version now works on apex.oracle.com, for me at least. At what environment are you installing it?

**Comment by p3t3r** [comment]
Oracle APEX 5.1.4 on a 11.2.0.4.0 database.

Seems the function is not created. At what moment is the function created?

**Comment by antonscheffer** [comment]
When you run the plugin. The plugin calls the function, if it doesn't exists it tries to create it and calls the function again. Not even an invalid function created, with lacking privileges for other packages for instance?

**Comment by p3t3r** [comment]
Think I figured it out , it checks for "PLS-00201: identifier " error, but I'm running a dutch localized db. So the error becomes "PLS-00201: identificatiesymbool".
I now manually installed the function.

But now another error :(
Error: SyntaxError: Unexpected token S in JSON at position 0

But I don't see an error in the APEX debug

**Comment by antonscheffer** [comment]
That could be related to the "optimized page processing" of APEX 5.1.4, see https://joelkallman.blogspot.com/2017/12/errors-when-downloading-file-on-page.html

**Comment by p3t3r** [comment]
Thanks that solved that issue.
