### ISSUE TITLE
Is it possible to set worksheet name(s) in the resulting workbook to be IR region name(s) ?

### ISSUE THREAD

**Issue by Joe-Barry** [antonscheffer/APEX2XLSX#6]
Hi,

Evaluated this plug-in ; great stuff.

https://github.com/antonscheffer/APEX2XLSX/blob/master/plugin/process_type_plugin_scheffer_apex_xlsx.sql

I am wondering now a hopefully simple question: how do we include the worksheet name(s) in the resulting workbook so that it could be the respective region name(s) for the worksheet tab names ? Maybe there is not a way yet but it would be fantastic.

[@anton-scheffer](https://forums.oracle.com/ords/apexds/user/anton-scheffer)

https://forums.oracle.com/ords/apexds/user/anton-scheffer

**Comment by antonscheffer** [comment]
No, that is not possible. And I will never change this plugin. You do realize that this plugin is created for APEX 4.0.2?
APEX has improved since then. If you need the data from a report region I would advise to use either the "download as Excel"-functionality or apex_region.data_export function.

**Comment by Joe-Barry** [comment]
Anton - thanks for the reply.

We highly value the plug-in for its multi-sheet capability into a single true workbook .xlsx despite it being 5 years old. It is still remarkably close to the base requirement for us, indeed.

We will see if we can loop or otherwise accommodate a single true xlsx workbook from many regions-of-a-page.   I seem to have learned too that the .xml templates(?) that go into a true .xlsx workbook may be subject to flux as well.

Thank You,

Joseph Barry

**Comment by antonscheffer** [comment]
I would suggest using as_xlsx to create a xlsx with multiple sheets in combination with some APEX packages: 
looping report regions, use apex_region.open_query_context
  looping the data of that context with apex_exec.next__row to_get all rows
    looping the row with apex_exec.get_... to get all the data cell values

**Comment by Joe-Barry** [comment]
Anton - ok.

Risk-free : does as_xlsx operate without creating directories ?  Can we maintain a blob in the APEX session somwhow without writing that out?  We're anti-directory at this point if we can avoid that additional complexity.

Thank You,

Joseph Barry

**Comment by Joe-Barry** [comment]
PS we are aiming for pure session until a download of an xlsx ( or zip) ;  no worries.  It's an honor to get a reply from you.  All the best.

Thank You,

Joseph Barry

From: Barry, Joseph
Sent: Monday, December 4, 2023 5:50 PM
To: antonscheffer/APEX2XLSX ***@***.***>; antonscheffer/APEX2XLSX ***@***.***>
Cc: Author ***@***.***>; Surya, Lydia CTR ***@***.***>
Subject: RE: [antonscheffer/APEX2XLSX] Is it possible to set worksheet name(s) in the resulting workbook to be IR region name(s) ? (Issue #6)

Anton - ok.

Risk-free : does as_xlsx operate without creating directories ?  Can we maintain a blob in the APEX session somwhow without writing that out?  We're anti-directory at this point if we can avoid that additional complexity.

Thank You,

Joseph Barry
